trigger:
  - main

pool:
  name: 'gurupool' 

steps:
  - script: terraform init
    displayName: 'Terraform Init'

  - script: terraform fmt -recursive
    displayName: 'Terraform Fmt'

  - script: terraform validate
    displayName: 'Terraform Validate'

  - script: terraform plan -out=tfplan
    displayName: 'Terraform Plan'

  - script: terraform apply -auto-approve tfplan
    displayName: 'Terraform Apply'