trigger:
  - main

pool:
  gurupool

variables:
  TF_VERSION: '1.6.6'  # apne version ke hisaab se change kar sakte ho

steps:
  - task: UseTerraform@0
    inputs:
      terraformVersion: $(TF_VERSION)

  - script: terraform init
    displayName: 'Terraform Init'

  - script: terraform fmt -check
    displayName: 'Terraform Format Check'

  - script: terraform validate
    displayName: 'Terraform Validate'

  - script: terraform plan -out=tfplan
    displayName: 'Terraform Plan'

  - script: terraform apply -auto-approve tfplan
    displayName: 'Terraform Apply'
